docs(README): add `usage` section explaining all options/flags
wharfix/wharfix pull request #98
Opened 2024-02-20 09:32 UTC by cafkafk

Signed-off-by: Christina Sørensen <christina@cafkafk.com>

2024-02-20 09:47 UTC, srhb requested changes

2024-02-20 09:47 UTC, srhb commented on README.md
> +To use substituters for internal wharfix calls to `nix-build`, use the `--subtituters <substituters>` option to specify a comma-separated list of nix substituters.
```suggestion
To use substituters for internal wharfix calls to `nix-build`, use the `--substituters <substituters>` option to specify a comma-separated list of nix substituters.
```

2024-02-20 09:47 UTC, srhb commented on README.md
> +To access ssh authentication based repositories, specify a ssh private key with `--ssh-private-key <sshprivatekey`.
```suggestion
To access ssh authentication based repositories, specify a ssh private key with `--ssh-private-key <sshprivatekey>`.
```

2024-02-20 09:53 UTC, srhb approved these changes

2024-02-20 09:53 UTC, merged

2024-02-22 10:58 UTC, johanot commented
Thanks a lot for this :100: 

Thought: Should we break the huge cmdline api once and for all and introduce a config file instead? :) tbh, the cmdline was fine when wharfix only had a couple of different run modes, but as more and more "serve-types" and "index-types" etc. creeped in, inter-dependencies between cmdline flags became more and more confusing.

2024-02-22 11:08 UTC, cafkafk commented
> Thought: Should we break the huge cmdline api once and for all and introduce a config file instead? :) tbh, the cmdline was fine when wharfix only had a couple of different run modes, but as more and more "serve-types" and "index-types" etc. creeped in, inter-dependencies between cmdline flags became more and more confusing.

Having them isn't inherently bad, I don't think it should be either/or, ideally wharfix would be best with both (with cmdline overriding config if both are specified). And if inter-dependencies are confusing, wouldn't they also be for a config file?

2024-02-22 11:35 UTC, johanot commented
> And if inter-dependencies are confusing, wouldn't they also be for a config file?

From my point of view at least, some of the confusion would go away with structured attrs, like:

```nix
{
   serve = {
     type.db.connFile = "db.conn";
     indexFilePath = "foo/bar.nix";
   };
}
```

1) Not only is it easier to see what "mode" wharfix is in - from the config itself - without having the "side-effect" that wharfix actually switches modes if you specify a dbconn-file. (you could perhaps achieve the same on the cmdline with requiring explicit `--serve-type` or structuring flags into subcommands?)

2) You also get better compile time and runtime checks of the config. Using generics for sevetype and nesting required options below impl types. (you could perhaps achieve the same with moving to clap struct pattern?). The problem is currently, imho, that it's easy to forget or misspell config dependencies, e.g. `.required_unless_one(&["lulzthiswilltotallyneverfail", "repo", "dbconnfile", "derivationoutput"]))`

> ideally wharfix would be best with both (with cmdline overriding config if both are specified)

I don't know whether the extra maintenance would be worth it, honestly? I kinda have allergies for complicated config resolution. Next up: Someone comes asking for adding env vars to the mix :) In that case, I think I would prefer it simple and settle with just improving the cmdline arg structure.

Aaaaaaanyway... tldr; it was just a thought - not really important.